// Generated by CoffeeScript 1.10.0

/*
{% load static %}
 */

(function() {
  var CACHE_NAME, REQUIRED_FILES;

  CACHE_NAME = 'dependencies-cache';

  REQUIRED_FILES = ["/contactlist/offline/", "/service_serviceworker.js", "{% static 'js/riot_compiler.min.js' %}", "{% static 'js/riotcontrol.js' %}", "{% static 'js/personstore.js' %}", "{% static 'js/requeststore.js' %}", "{% static 'js/jquery-2.1.4.min.js' %}", "{% static 'js/Lawnchair.js' %}", "{% static 'js/adapters/indexed-db.js' %}", "{% static 'css/bootstrap.min.css' %}", "{% static 'js/get_csrftoken.js' %}"];

  self.addEventListener('install', function(event) {
    event.waitUntil(caches.open(CACHE_NAME).then(function(cache) {
      return cache.addAll(REQUIRED_FILES);
    }).then(function() {
      return self.skipWaiting();
    }));
  });

  self.addEventListener('fetch', function(event) {
    event.respondWith(caches.match(event.request).then(function(response) {
      if (response) {
        return response;
      }
      return fetch(event.request);
    }));
  });

  self.addEventListener('activate', function(event) {
    event.waitUntil(self.clients.claim());
  });

}).call(this);
